USE [master]
GO

/****** Object:  Database [ElizabethLoparcoDB]    Script Date: 5/27/2024 3:18:17 PM ******/
CREATE DATABASE [ElizabethLoparcoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ElizabethLoparcoDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ElizabethLoparcoDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ElizabethLoparcoDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\ElizabethLoparcoDB_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ElizabethLoparcoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ElizabethLoparcoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET  MULTI_USER 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ElizabethLoparcoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ElizabethLoparcoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ElizabethLoparcoDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [ElizabethLoparcoDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ElizabethLoparcoDB] SET  READ_WRITE 
GO

